### ISSUE TITLE
There is no toplevel README for this project, explaining what it does

### ISSUE THREAD

**Issue by DinoChiesa** [jrockway/eproject#69]
What does eproject do? 
What is better when I use eproject?

**Comment by sten0** [comment]
Dear eproject maintainer,

I have packaged eproject for Debian, and this would be really nice to have.

Cheers,
Nicholas

**Comment by andyleejordan** [comment]
The project's readme is in the typical location for Emacs Lisp packages, [in the header under commentary](https://github.com/jrockway/eproject/blob/068218d2cf2138cb2e8fc29b57e773a0097a7e8b/eproject.el#L31). Sure, it doesn't show up on GitHub on the front page, and that'd be nice, but this project has both a license and readme in the correct locations per [Emacs library conventions](https://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html#Library-Headers).
